In [1]:
import pandas as pd
import numpy as np

In [13]:
df_prices = pd.read_csv('hotel_prices.csv')
df_prices.head()

   impressions       price
0         5001   98.648791
1         5002   98.278646
2         5003  121.986502
3         5004  149.591013
4         5005  135.900000

In [12]:
df_grouped = df_prices.groupby('impressions')['prices'].mean().reset_index(name='price')
print('File iniziale: ' + str(df_prices.shape[0]) + ' Finale: ' + str(df_grouped.shape[0]))
df_grouped.head()
df_grouped.to_csv('hotel_prices.csv', index=False)

File iniziale: 3176809 Finale: 875008

In [16]:
df_prices[df_prices['impressions'] == 107162]

       impressions       price
56366       107162  129.682205

In [17]:
df_prices[df_prices['impressions'] == 3184892]

        impressions      price
316799      3184892  91.358678

In [2]:
df_train = pd.read_csv('train_off.csv')
df_test = pd.read_csv('test_off.csv')

In [3]:
df_tot = pd.concat([df_train, df_test], ignore_index=True)

In [8]:
df_tot[df_tot['user_id'] == 'SS4INACFPWUX']

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
16040700,SS4INACFPWUX,babd8de326bf5,1541587168,1,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040701,SS4INACFPWUX,babd8de326bf5,1541587168,2,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040702,SS4INACFPWUX,babd8de326bf5,1541587168,3,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040703,SS4INACFPWUX,babd8de326bf5,1541587168,4,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040704,SS4INACFPWUX,babd8de326bf5,1541587178,5,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040705,SS4INACFPWUX,babd8de326bf5,1541587178,6,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040706,SS4INACFPWUX,babd8de326bf5,1541587188,7,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040707,SS4INACFPWUX,babd8de326bf5,1541587188,8,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040708,SS4INACFPWUX,babd8de326bf5,1541587188,9,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040709,SS4INACFPWUX,babd8de326bf5,1541587188,10,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040710,SS4INACFPWUX,babd8de326bf5,1541587198,11,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040711,SS4INACFPWUX,babd8de326bf5,1541587198,12,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040712,SS4INACFPWUX,babd8de326bf5,1541587198,13,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040713,SS4INACFPWUX,babd8de326bf5,1541587198,14,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040714,SS4INACFPWUX,babd8de326bf5,1541587198,15,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040715,SS4INACFPWUX,babd8de326bf5,1541587198,16,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040716,SS4INACFPWUX,babd8de326bf5,1541587208,17,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040717,SS4INACFPWUX,babd8de326bf5,1541587208,18,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040718,SS4INACFPWUX,babd8de326bf5,1541587208,19,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040719,SS4INACFPWUX,babd8de326bf5,1541587208,20,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040720,SS4INACFPWUX,babd8de326bf5,1541587218,21,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040721,SS4INACFPWUX,babd8de326bf5,1541587218,22,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040722,SS4INACFPWUX,babd8de326bf5,1541587218,23,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040723,SS4INACFPWUX,babd8de326bf5,1541587218,24,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040724,SS4INACFPWUX,babd8de326bf5,1541587218,25,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040725,SS4INACFPWUX,babd8de326bf5,1541587218,26,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040726,SS4INACFPWUX,babd8de326bf5,1541587228,27,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040727,SS4INACFPWUX,babd8de326bf5,1541587228,28,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040728,SS4INACFPWUX,babd8de326bf5,1541587228,29,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040729,SS4INACFPWUX,babd8de326bf5,1541587228,30,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040730,SS4INACFPWUX,babd8de326bf5,1541587228,31,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040731,SS4INACFPWUX,babd8de326bf5,1541587228,32,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040732,SS4INACFPWUX,babd8de326bf5,1541587238,33,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040733,SS4INACFPWUX,babd8de326bf5,1541587238,34,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040734,SS4INACFPWUX,babd8de326bf5,1541587238,35,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040735,SS4INACFPWUX,babd8de326bf5,1541587248,36,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040736,SS4INACFPWUX,babd8de326bf5,1541587248,37,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040737,SS4INACFPWUX,babd8de326bf5,1541587248,38,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040738,SS4INACFPWUX,babd8de326bf5,1541587248,39,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040739,SS4INACFPWUX,babd8de326bf5,1541587248,40,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040740,SS4INACFPWUX,babd8de326bf5,1541587248,41,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040741,SS4INACFPWUX,babd8de326bf5,1541587258,42,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040742,SS4INACFPWUX,babd8de326bf5,1541587258,43,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040743,SS4INACFPWUX,babd8de326bf5,1541587258,44,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040744,SS4INACFPWUX,babd8de326bf5,1541587268,45,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040745,SS4INACFPWUX,babd8de326bf5,1541587268,46,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040746,SS4INACFPWUX,babd8de326bf5,1541587268,47,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040747,SS4INACFPWUX,babd8de326bf5,1541587268,48,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040748,SS4INACFPWUX,babd8de326bf5,1541587268,49,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040749,SS4INACFPWUX,babd8de326bf5,1541587268,50,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040750,SS4INACFPWUX,babd8de326bf5,1541587268,51,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040751,SS4INACFPWUX,babd8de326bf5,1541587278,52,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040752,SS4INACFPWUX,babd8de326bf5,1541587278,53,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040753,SS4INACFPWUX,babd8de326bf5,1541587278,54,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040754,SS4INACFPWUX,babd8de326bf5,1541587278,55,interaction item image,2556084,AU,"Holbrook, Australia",mobile,NaN,NaN,NaN
16040755,SS4INACFPWUX,babd8de326bf5,1541587369,56,clickout item,NaN,AU,"Holbrook, Australia",mobile,NaN,2049967,82

In [9]:
df_train[df_train['user_id'] == 'OKEDW4LHMKDO']

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
11269963,OKEDW4LHMKDO,6d16cf00de49e,1541076767,1,interaction item deals,678691,AT,"Bang Tao Beach, Thailand",desktop,NaN,NaN,NaN

In [12]:
df_test[df_test['user_id'] == 'LJKUJY87L893']

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
104199,LJKUJY87L893,5aaee7d4682dd,1541661264,1,filter selection,Hostal (ES),PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104200,LJKUJY87L893,5aaee7d4682dd,1541661264,2,filter selection,Hotel,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104201,LJKUJY87L893,5aaee7d4682dd,1541661264,3,filter selection,Motel,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104202,LJKUJY87L893,5aaee7d4682dd,1541661264,4,filter selection,Resort,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104203,LJKUJY87L893,5aaee7d4682dd,1541661264,5,filter selection,3 Star,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104204,LJKUJY87L893,5aaee7d4682dd,1541661264,6,filter selection,4 Star,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104205,LJKUJY87L893,5aaee7d4682dd,1541661264,7,filter selection,5 Star,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104206,LJKUJY87L893,5aaee7d4682dd,1541661265,8,filter selection,Very Good Rating,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104207,LJKUJY87L893,5aaee7d4682dd,1541661273,9,filter selection,Free WiFi (Combined),PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104208,LJKUJY87L893,5aaee7d4682dd,1541661275,10,filter selection,Swimming Pool (Combined Filter),PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104209,LJKUJY87L893,5aaee7d4682dd,1541661285,11,filter selection,Swimming Pool (Combined Filter),PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104210,LJKUJY87L893,5aaee7d4682dd,1541661305,12,interaction item rating,4673228,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104211,LJKUJY87L893,5aaee7d4682dd,1541661340,13,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104212,LJKUJY87L893,5aaee7d4682dd,1541661340,14,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104213,LJKUJY87L893,5aaee7d4682dd,1541661350,15,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104214,LJKUJY87L893,5aaee7d4682dd,1541661350,16,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104215,LJKUJY87L893,5aaee7d4682dd,1541661350,17,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104216,LJKUJY87L893,5aaee7d4682dd,1541661350,18,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104217,LJKUJY87L893,5aaee7d4682dd,1541661350,19,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104218,LJKUJY87L893,5aaee7d4682dd,1541661350,20,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104219,LJKUJY87L893,5aaee7d4682dd,1541661359,21,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104220,LJKUJY87L893,5aaee7d4682dd,1541661359,22,interaction item image,4377656,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104221,LJKUJY87L893,5aaee7d4682dd,1541661360,23,filter selection,Excellent Rating,PE,"Ica, Peru",desktop,5 Star|4 Star|3 Star|Hotel|Motel|Resort|Hostal...,NaN,NaN
104222,LJKUJY87L893,5aaee7d4682dd,1541661370,24,filter selection,Hostal (ES),PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104223,LJKUJY87L893,5aaee7d4682dd,1541661370,25,filter selection,Hotel,PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104224,LJKUJY87L893,5aaee7d4682dd,1541661370,26,filter selection,Motel,PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104225,LJKUJY87L893,5aaee7d4682dd,1541661370,27,filter selection,Resort,PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104226,LJKUJY87L893,5aaee7d4682dd,1541661370,28,filter selection,4 Star,PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104227,LJKUJY87L893,5aaee7d4682dd,1541661370,29,filter selection,5 Star,PE,"Ica, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104228,LJKUJY87L893,5aaee7d4682dd,1541661380,30,interaction item image,2590312,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104229,LJKUJY87L893,5aaee7d4682dd,1541661380,31,interaction item image,2590312,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104230,LJKUJY87L893,5aaee7d4682dd,1541661380,32,interaction item image,2590312,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104231,LJKUJY87L893,5aaee7d4682dd,1541661380,33,interaction item image,2590312,PE,"Ica, Peru",desktop,NaN,NaN,NaN
104232,LJKUJY87L893,5aaee7d4682dd,1541661395,34,search for destination,"Lunahuana, Peru",PE,"Lunahuana, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104233,LJKUJY87L893,5aaee7d4682dd,1541661410,35,change of sort order,interaction sort button,PE,"Lunahuana, Peru",desktop,NaN,NaN,NaN
104234,LJKUJY87L893,5aaee7d4682dd,1541661414,36,change of sort order,price and recommended,PE,"Lunahuana, Peru",desktop,NaN,NaN,NaN
104235,LJKUJY87L893,5aaee7d4682dd,1541661414,37,filter selection,Best Value,PE,"Lunahuana, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|F...,NaN,NaN
104236,LJKUJY87L893,5aaee7d4682dd,1541661418,38,filter selection,Free WiFi (Combined),PE,"Lunahuana, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Hostal (ES)|E...,NaN,NaN
104237,LJKUJY87L893,5aaee7d4682dd,1541661423,39,filter selection,Hostal (ES),PE,"Lunahuana, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104238,LJKUJY87L893,5aaee7d4682dd,1541661424,40,filter selection,Swimming Pool (Combined Filter),PE,"Lunahuana, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104239,LJKUJY87L893,5aaee7d4682dd,1541661444,41,search for destination,"Asia, Peru",PE,"Asia, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104240,LJKUJY87L893,5aaee7d4682dd,1541661454,42,filter selection,Free WiFi (Combined),PE,"Asia, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104241,LJKUJY87L893,5aaee7d4682dd,1541661466,43,filter selection,Swimming Pool (Combined Filter),PE,"Asia, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104242,LJKUJY87L893,5aaee7d4682dd,1541661484,44,filter selection,Excellent Rating,PE,"Asia, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,NaN,NaN
104243,LJKUJY87L893,5aaee7d4682dd,1541661484,45,clickout item,NaN,PE,"Asia, Peru",desktop,5 Star|4 Star|Hotel|Motel|Resort|Excellent Rat...,9666240|4034724,16|78

In [15]:
df_subm = pd.read_csv('submission_popular.csv')
df_subm[df_subm['user_id'] == "H23743N5Q334"]

,user_id,session_id,timestamp,step,item_recommendations
129726,H23743N5Q334,dc964e38fac3b,1541624849,6,55115 980153 667346 667241 5864140 6924278 719...
226404,H23743N5Q334,ca2e5b871a11e,1541559456,6,8386650|8818012

In [11]:
df_subm_off = pd.read_csv('submission_popular_off.csv')
df_subm.head()

,user_id,session_id,timestamp,step,item_recommendations
0,004A07DM0IDW,1d688ec168932,1541555799,7,2249874 1050068 3241426 2059240 399441 9030086...
1,00Y1Z24X8084,26b6d294d66e7,1541651823,2,3843244 9343000 1981001 4476010 7101352 779497...
2,01V3WDTDM5CU,07628a0f5be0b,1541575643,5,2817590 6434434 2012359 7950162 3180004 287562...
3,02AOAVF9PVYH,4a01c3afbc224,1541681278,46,2403128 559091 7304020 559056 1052958 559026 1...
4,0339C84S24ET,89171d441a304,1541615683,36,4500498 5647680 37717 5773306 4957186 9500346 ...

In [7]:
tot_elements = df_test[df_test['reference'].isnull()].shape[0]
one_session_clickout = df_test[(df_test['action_type'] == 'clickout item') & (df_test['step'] == 1) & (df_test['reference'].isnull())]
print('There are #' + str(tot_elements) + ' in the test set')
print('# ' + str(one_session_clickout.shape[0]) + ' are clickout at the first step')
print('# ' + str(tot_elements - one_session_clickout.shape[0]) + ' are standard sessions')

There are #261731 in the test set
# 60605 are clickout at the first step
# 201126 are standard sessions

In [6]:
one_session_clickout.head()

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
513,0BZN2KFMHLZF,d9497eeb946dc,1541668916,1,clickout item,NaN,BE,"Hasselt, Belgium",mobile,NaN,39730|133101|39758|7029236|455086|3887112|1070...,90|88|80|80|90|62|65|90|89|75|70|109|165|104|6...
554,0D1XFBRWUX7Z,35e873299a45f,1541586069,1,clickout item,NaN,AU,"Sydney, Australia",mobile,NaN,54865|54803|54953|14211|95510|54838|54794|1484...,163|126|158|177|145|85|107|158|132|189|187|131...
598,0EPVF4QE049Q,11b583578f7f3,1541611766,1,clickout item,NaN,FI,"Seinäjoki, Finland",mobile,NaN,368306|369426|4916202|2045589|1328820|369421|1...,123|152|59|148|105|147|98|70|95|80|140
599,0GY71I4BUBQW,334177bbc6525,1541638087,1,clickout item,NaN,AU,"Rome, Italy",desktop,NaN,17112|1374294|17382|2321776|16895|17056|17108|...,81|95|126|79|186|112|53|112|56|214|142|77|71|1...
600,0H2RFN3FXM5A,e9fa318e4aad0,1541576918,1,clickout item,NaN,IN,"Bengaluru, India",mobile,NaN,1984531|4775794|1400686|930783|2612414|1199716...,37|16|19|50|148|16|157|14|21|19|14|16|16|22|13...